# VLC と同じ再生エンジン（Android 版の libVLC の iPhone 版）
platform :ios, '16.0'
use_frameworks!

target 'Orbit' do
  pod 'MobileVLCKit', '~> 3.6'
end

post_install do |installer|
  installer.pods_project.targets.each do |t|
    t.build_configurations.each do |c|
      c.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
    end
  end
end
